runtime: nodejs12
automatic_scaling:
min_idle_instances: automatic
max_idle_instances: 1
min_pending_latency: 3000ms
max_pending_latency: automatic
handlers:
- url: /login
secure: always
redirect_http_response_code: 301
script: auto